// <auto-generated />
using System;
using ECommerceProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceProjectBackend.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20250310185911_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ECommerceProject.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("commentId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commentText");

                    b.Property<string>("CommentTitle")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("commentTitle");

                    b.Property<int>("UserUserId")
                        .HasColumnType("int")
                        .HasColumnName("User_userId");

                    b.HasKey("CommentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CommentId" }, "commentId_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "UserUserId" }, "fk_Comment_User1_idx");

                    b.ToTable("Comment", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("ECommerceProject.Models.PaymentInfo", b =>
                {
                    b.Property<int>("PaymentInfoId")
                        .HasColumnType("int")
                        .HasColumnName("paymentInfoId");

                    b.Property<int?>("PaymentInfoCreditCardNumber")
                        .HasColumnType("int")
                        .HasColumnName("paymentInfoCreditCardNumber");

                    b.Property<string>("PaymentInfoCreditCardUserName")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("paymentInfoCreditCardUserName");

                    b.Property<string>("PaymentInfoCvv")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("paymentInfoCVV");

                    b.Property<string>("PaymentInfoExpirationDate")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("paymentInfoExpirationDate");

                    b.Property<string>("PaymentInfoTitle")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("paymentInfoTitle");

                    b.Property<int>("UserUserId")
                        .HasColumnType("int")
                        .HasColumnName("User_userId");

                    b.HasKey("PaymentInfoId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserUserId" }, "fk_PaymentInfo_User1_idx");

                    b.ToTable("PaymentInfo", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("ECommerceProject.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CommentCommentId")
                        .HasColumnType("int")
                        .HasColumnName("Comment_commentId");

                    b.Property<string>("ProductCategory")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("text")
                        .HasColumnName("productDescription");

                    b.Property<byte[]>("ProductImage")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("int")
                        .HasColumnName("productPrice");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("productTitle");

                    b.Property<int>("SellerSellerId")
                        .HasColumnType("int")
                        .HasColumnName("Seller_sellerId");

                    b.HasKey("ProductId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CommentCommentId" }, "fk_Product_Comment1_idx");

                    b.HasIndex(new[] { "SellerSellerId" }, "fk_Product_Seller1_idx");

                    b.HasIndex(new[] { "ProductId" }, "productId_UNIQUE")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("ECommerceProject.Models.Seller", b =>
                {
                    b.Property<int>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sellerId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SellerId"));

                    b.Property<float?>("SellerRating")
                        .HasColumnType("float")
                        .HasColumnName("sellerRating");

                    b.Property<string>("SellerTitle")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("sellerTitle");

                    b.Property<int>("UserUserId")
                        .HasColumnType("int")
                        .HasColumnName("User_userId");

                    b.HasKey("SellerId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserUserId" }, "fk_Seller_User1_idx");

                    b.ToTable("Seller", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("ECommerceProject.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserBirthDate")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("userBirthDate");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("userEmail");

                    b.Property<sbyte>("UserGender")
                        .HasColumnType("tinyint")
                        .HasColumnName("userGender");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("userName");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("userPassword");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserEmail" }, "userEmail_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "userId_UNIQUE")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("ECommerceProject.Models.Comment", b =>
                {
                    b.HasOne("ECommerceProject.Models.User", "UserUser")
                        .WithMany("Comments")
                        .HasForeignKey("UserUserId")
                        .IsRequired()
                        .HasConstraintName("fk_Comment_User1");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("ECommerceProject.Models.PaymentInfo", b =>
                {
                    b.HasOne("ECommerceProject.Models.User", "UserUser")
                        .WithMany("PaymentInfos")
                        .HasForeignKey("UserUserId")
                        .IsRequired()
                        .HasConstraintName("fk_PaymentInfo_User1");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("ECommerceProject.Models.Product", b =>
                {
                    b.HasOne("ECommerceProject.Models.Comment", "CommentComment")
                        .WithMany("Products")
                        .HasForeignKey("CommentCommentId")
                        .IsRequired()
                        .HasConstraintName("fk_Product_Comment1");

                    b.HasOne("ECommerceProject.Models.Seller", "SellerSeller")
                        .WithMany("Products")
                        .HasForeignKey("SellerSellerId")
                        .IsRequired()
                        .HasConstraintName("fk_Product_Seller1");

                    b.Navigation("CommentComment");

                    b.Navigation("SellerSeller");
                });

            modelBuilder.Entity("ECommerceProject.Models.Seller", b =>
                {
                    b.HasOne("ECommerceProject.Models.User", "UserUser")
                        .WithMany("Sellers")
                        .HasForeignKey("UserUserId")
                        .IsRequired()
                        .HasConstraintName("fk_Seller_User1");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("ECommerceProject.Models.Comment", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerceProject.Models.Seller", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerceProject.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PaymentInfos");

                    b.Navigation("Sellers");
                });
#pragma warning restore 612, 618
        }
    }
}
